apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
spec:
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the service
      targetPort: 5000 # Port on the pods/containers
  type: LoadBalancer # Use LoadBalancer for cloud environments, or NodePort for others
